version: "3.8"

services:
  app:
    build: .
    container_name: bloodlink-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5001:5001"
    depends_on:
      - redis
    networks:
      - backend-net
    environment:
      - NODE_ENV=production
    command: ["node", "index.js"]  # Corrected entry point

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge
